# This file overrides the file from docker-compose.yml

version: "3"

services:
    phpmyadmin:
        ports:
            - "8079:80"

    wordpress:
        ports:
            - "80:80"
        volumes:
            - ../../:/var/www/html/wp-content/plugins/wp-reactjs-starter
